const tags = ["","#christmascat","2cats","3","4","@Beardlyness","Beer","Belfast",
"BelfastMet","Black","Buckley","Cat","Cat in a faucet","Catto","Chair","CryptoWorld Cat",
"Curious","Cute","Dark","FAT","Friends","Fulgencio","Going shopping?","Grumpy","Hiding",
"Lay","Luz","Maine coon","Maskcat","Mimi","NSFW","Orange","Outside","Ragdoll","Relaxed",
"Roar","Sad","Shhhsh","Sleepy","Summer","Tabby","Tassilo","Teeth","Tired cat","TorWorld Cat",
"Trippy","Unside down","White","X-MAS","Yeet","advent-calendar-2016","afraid","alcoholic",
"alien","ange","angel","angry","annilou91","anstrengend","are","artist","attack","attention",
"attitude","ava","baby","background","banzai","basin","bath","beautiful","bed","beer","beg",
"begging","belly","belly rubs","bengal","big","big-eyes","bird","black","black an white",
"black and white","blue","blur","blurred","boot","box","boxe","british shorthair","british-shorthair"
,"brown","bubble","bucket","bun","burrito","burrito-cat","bw","calico","calvin","cash","cat",
"cat eyes","cat face","cat kneading","cat_winston","catloaf","cats","catto","chat","check",
"chonker","christmas","climb","closeup","coat","color","colorful","comfy","computer","confused",
"cool","costume","couch","cow","cowboy","crazy","crazy russian pussycat","creation","crying",
"cryptid","cuddle","cuddles","cup","curl","cut","cute","cute baby smol small","cutie","dance",
"dark","dark vador","darth","darth vader","davie412","dead","derp","detective","dev","devcat",
"dictator","didizin","dinner!","disappointed","dj","dogstyle","down","dream","drone","drugs",
"drunk","engineer","evil","exferal","eyes","facecat","fail","fat","fat cat","fedora","felix",
"file","floor","fluffy","flying","fold","food","freeze","front_view","fun","funny","furious",
"gg","gif","ginger","glow","goofy","gray","group","grump","grumpy","guilty","gun","halloween",
"happy","hard","hat","headinacup","hedgehog","hello","hi","hide","high_quality","ho","ho-wait",
"howcanihelp","hug","huge","hulu","hunger","icecream","jellybean toes toe beans grey gray mauve",
"jellybean toes toebeans squished beans","judgemental","jump","jumping","kick","kiss","kitler",
"kitten","kittenleg","kittens","kitty","knocknoc","kucing","kuro","laying","legs","lights","loaf",
"logan","lolcat","long","long-cat","lying down","mackerel tabby","mad","mama","marine","mask",
"meme","metal","misty","mixed","money","moody","morrigan","morrigan witch of the wilds","mousecat",
"multi","multiple_colors","munchkin","nasty","nelly","newyear","nicecat","no","nope","nyancat",
"nyancat-gif","old","ominous","orange","orange cat","ovni","pain","party","patoka","paw","petting",
"piano","pic","pippin","pirate","playful","please","plot","portrait-worthy","pretty","professional",
"programmer","puffy","quality","reading","resting","rich","roll","rolling","running","russia",
"russian blue","sad","sad catto","samurai","sassy","savannah","screm","seeya!","selfie","serious",
"shark","shit","siamese","sideways","silly","sing","sitting up","sleep","sleeping","sleepy","slick",
"small","smile","smirk","smol","smug","sofa","soft","some","soon","sound","space","spots","square",
"stair","staline","star wars","startled","strawberry","stretch","stripes","stupid","stupids","suicide",
"summon","supermodel","surprised","tabby","tair","tech","thief","tinny","tongue","tortie",
"tortoiseshell cat","toys","triggered","trump","tryhard","tryhard_cat","tux","tuxedo","tuxedo cat",
"twitter","twoface","typing","ugg","ugly","unicorn","unit","uwu","vader","vador","victorious-cat",
"victory","waiting","wakup","walking","water","watter cat","weinstein","white","white_fur","window",
"witch","worker","workspace","wtf","xena","yang","yeay","ying","yoga","young","zombie","なら"];

export const getRandomTag = () => {
   const randomIndex = Math.floor(Math.random() * 386) + 1;
   return tags[randomIndex];
};